version: "3"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/code
    restart: on-failure
    env_file: .env
    ports:
      - "8000:8000"
  database:
    image: postgres:14.1-alpine
    restart: always
    env_file: .env
    ports:
      - '5433:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    depends_on:
      - web


